### ISSUE TITLE
Bad position of "play" icon

### ISSUE THREAD

**Issue by jgsogo** [madridccppug/meetups#22]
After merging #20 now we have a link to the Youtube video, but... it may need some CSS to position it.

![image](https://user-images.githubusercontent.com/1406456/51244189-b8e67800-1984-11e9-9b53-53eb5c9729e6.png)

**Comment by newlawrence** [comment]
Well... I think I should have paid more attention to that. The problem is related to the **Youtube** badge I chose to use, which I picked it from [this project](https://github.com/simple-icons/simple-icons) because I dind't wanted to start bloating the repository with external branding stuff. Now, I'm making some tests with the [icons provided by **Youtube** itself](https://github.com/simple-icons/simple-icons) and they seem to work better.

The question is, in which order do you think it is better to put the icon?

Afterwards?
![afterwards](https://user-images.githubusercontent.com/5416864/51246209-28ab3180-198a-11e9-8945-2cbc8bbf3fa2.png)

Beforewards?
![beforewards](https://user-images.githubusercontent.com/5416864/51246225-33fe5d00-198a-11e9-9c6c-0e5072bf6088.png)

In my honest opinion, I think afterwards looks prettier than beforewards; but I don't mind it which one to use at last. Also, I think the red color is more effective than the black one for the icon.

**Comment by jgsogo** [comment]
I prefer it afterward, and if possible I will fix the vertical alignment (and more horizontal space)... 

Maybe it is better to put it in another section after contents

```
Contents:
 * bla
 * bla
 * bla

Links: [youtube] [...]
```

**Comment by jgsogo** [comment]
Maybe a little bit smaller, but don't worry about it too much, we can change it in the future

**Comment by newlawrence** [comment]
What do you think about [this](https://github.com/newlawrence/Meetups/tree/39a45c948185af290441babd8adf8b3ab80771d3/2018-11-22_Liferay_MarketGoo)?

**Comment by jgsogo** [comment]
Nice! but now that I see it I wouldn't use a section, just a line: "Related content: <youtbue> <meetup> <blogpost from someone>", don't you think it is too much having a section?

**Comment by newlawrence** [comment]
Well, the problem again with using only a line is the alignment of the icons. In the last try, which you can see above, the icons align with the base line of the text. I'll give this another try and see the results.
